package in.invoizo.invoicegeneratorapi.service;

import in.invoizo.invoicegeneratorapi.entity.Invoice;
import in.invoizo.invoicegeneratorapi.entity.Invoice.InvoiceStatus;
import in.invoizo.invoicegeneratorapi.repository.InvoiceRepository;
import in.invoizo.invoicegeneratorapi.validator.StatusTransitionValidator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;

/**
 * Service for managing invoice status lifecycle automation
 * Handles automatic status transitions based on business events
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class InvoiceStatusService {

    private final InvoiceRepository invoiceRepository;
    private final StatusTransitionValidator statusTransitionValidator;
    private final RazorpayService razorpayService;

    /**
     * Auto-save invoice as DRAFT
     * Called when user creates invoice or fills minimum fields
     */
    @Transactional
    public Invoice saveDraft(Invoice invoice, String clerkId) {
        log.info("Auto-saving invoice as DRAFT for user: {}", clerkId);
        
        // Set clerk ID if not already set
        if (invoice.getClerkId() == null) {
            invoice.setClerkId(clerkId);
        }
        
        // Set status to DRAFT if new invoice
        if (invoice.getId() == null) {
            invoice.setStatus(InvoiceStatus.DRAFT);
            invoice.setIsAutoGeneratedStatus(true);
            invoice.setLastStatusUpdatedAt(Instant.now());
        }
        
        return invoiceRepository.save(invoice);
    }

    /**
     * Transition invoice from DRAFT to SENT
     * Called when invoice is emailed to customer
     * Also generates Razorpay payment link
     */
    @Transactional
    public Invoice markAsSent(String invoiceId, String clerkId) {
        log.info("Marking invoice {} as SENT", invoiceId);
        
        Invoice invoice = invoiceRepository.findByClerkIdAndId(clerkId, invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + invoiceId));
        
        // Validate transition
        InvoiceStatus currentStatus = invoice.getStatus() != null ? invoice.getStatus() : InvoiceStatus.DRAFT;
        statusTransitionValidator.validateTransition(currentStatus, InvoiceStatus.SENT);
        
        // Update status
        invoice.setStatus(InvoiceStatus.SENT);
        invoice.setEmailSentAt(Instant.now());
        invoice.setLastStatusUpdatedAt(Instant.now());
        invoice.setIsAutoGeneratedStatus(true);
        
        // Generate Razorpay payment link
        try {
            String paymentLink = razorpayService.generatePaymentLink(invoice);
            if (paymentLink != null) {
                if (invoice.getPaymentDetails() == null) {
                    invoice.setPaymentDetails(new Invoice.PaymentDetails());
                }
                invoice.getPaymentDetails().setPaymentLink(paymentLink);
                invoice.getPaymentDetails().setPaymentStatus(Invoice.PaymentStatus.PENDING);
                invoice.getPaymentDetails().setPaymentLinkCreatedAt(Instant.now());
                
                // Generate QR code data
                String qrData = razorpayService.generateQRData(paymentLink);
                invoice.getPaymentDetails().setQrCodeData(qrData);
                
                log.info("Payment link generated for invoice {}: {}", invoiceId, paymentLink);
            }
        } catch (Exception e) {
            log.error("Failed to generate payment link for invoice {}", invoiceId, e);
            // Continue without payment link - don't fail the entire operation
        }
        
        return invoiceRepository.save(invoice);
    }

    /**
     * Mark invoice as VIEWED
     * Called when customer opens the invoice (tracking pixel or page view)
     */
    @Transactional
    public Invoice markAsViewed(String invoiceId) {
        log.info("Marking invoice {} as VIEWED", invoiceId);
        
        Invoice invoice = invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + invoiceId));
        
        // Only update if not already viewed and status is SENT
        if (invoice.getFirstViewedAt() == null && invoice.getStatus() == InvoiceStatus.SENT) {
            invoice.setStatus(InvoiceStatus.VIEWED);
            invoice.setFirstViewedAt(Instant.now());
            invoice.setLastStatusUpdatedAt(Instant.now());
            invoice.setIsAutoGeneratedStatus(true);
            
            return invoiceRepository.save(invoice);
        }
        
        return invoice;
    }

    /**
     * Mark invoice as PAID
     * Called from Razorpay webhook when payment is successful
     */
    @Transactional
    public Invoice markAsPaid(String invoiceId, String paymentId, String orderId, 
                              Invoice.PaymentMethod paymentMethod, String webhookEventId) {
        log.info("Marking invoice {} as PAID (paymentId: {})", invoiceId, paymentId);
        
        Invoice invoice = invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + invoiceId));
        
        // Check for idempotency - if already processed this webhook event
        if (invoice.getPaymentDetails() != null && 
            webhookEventId.equals(invoice.getPaymentDetails().getWebhookEventId())) {
            log.info("Webhook event {} already processed for invoice {}", webhookEventId, invoiceId);
            return invoice;
        }
        
        // Validate transition
        InvoiceStatus currentStatus = invoice.getStatus() != null ? invoice.getStatus() : InvoiceStatus.DRAFT;
        statusTransitionValidator.validateTransition(currentStatus, InvoiceStatus.PAID);
        
        // Update status
        invoice.setStatus(InvoiceStatus.PAID);
        invoice.setPaidAt(Instant.now());
        invoice.setLastStatusUpdatedAt(Instant.now());
        invoice.setIsAutoGeneratedStatus(true);
        
        // Update payment details
        if (invoice.getPaymentDetails() == null) {
            invoice.setPaymentDetails(new Invoice.PaymentDetails());
        }
        invoice.getPaymentDetails().setPaymentStatus(Invoice.PaymentStatus.SUCCESS);
        invoice.getPaymentDetails().setRazorpayPaymentId(paymentId);
        invoice.getPaymentDetails().setRazorpayOrderId(orderId);
        invoice.getPaymentDetails().setPaymentMethod(paymentMethod);
        invoice.getPaymentDetails().setPaymentDate(Instant.now());
        invoice.getPaymentDetails().setWebhookEventId(webhookEventId);
        
        return invoiceRepository.save(invoice);
    }

    /**
     * Mark invoice as OVERDUE
     * Called by scheduler when due date has passed
     */
    @Transactional
    public Invoice markAsOverdue(String invoiceId) {
        log.info("Marking invoice {} as OVERDUE", invoiceId);
        
        Invoice invoice = invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + invoiceId));
        
        // Only mark as overdue if status is SENT or VIEWED
        if (invoice.getStatus() == InvoiceStatus.SENT || invoice.getStatus() == InvoiceStatus.VIEWED) {
            invoice.setStatus(InvoiceStatus.OVERDUE);
            invoice.setLastStatusUpdatedAt(Instant.now());
            invoice.setIsAutoGeneratedStatus(true);
            
            return invoiceRepository.save(invoice);
        }
        
        return invoice;
    }

    /**
     * Manual cancellation (only manual action allowed)
     */
    @Transactional
    public Invoice markAsCancelled(String invoiceId, String clerkId) {
        log.info("Manually cancelling invoice {}", invoiceId);
        
        Invoice invoice = invoiceRepository.findByClerkIdAndId(clerkId, invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + invoiceId));
        
        // Validate transition
        InvoiceStatus currentStatus = invoice.getStatus() != null ? invoice.getStatus() : InvoiceStatus.DRAFT;
        statusTransitionValidator.validateTransition(currentStatus, InvoiceStatus.CANCELLED);
        
        invoice.setStatus(InvoiceStatus.CANCELLED);
        invoice.setCancelledAt(Instant.now());
        invoice.setLastStatusUpdatedAt(Instant.now());
        invoice.setIsAutoGeneratedStatus(false); // Manual action
        
        return invoiceRepository.save(invoice);
    }
}
