/**
 * Database Migration Script for Invoice Auto Status Sync
 * 
 * This script adds new fields to support automated invoice lifecycle management:
 * - Status tracking fields (status, timestamps)
 * - Payment integration fields (Razorpay IDs)
 * - Auto-generated status flag
 * 
 * Requirements: 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.10
 */

print("=== Starting Invoice Auto Status Sync Migration ===\n");

// Step 1: Add status field with default DRAFT for invoices without status
const invoicesWithoutStatus = db.invoices.countDocuments({ status: { $exists: false } });
if (invoicesWithoutStatus > 0) {
    db.invoices.updateMany(
        { status: { $exists: false } },
        {
            $set: {
                status: "DRAFT"
            }
        }
    );
    print("✓ Set status to DRAFT for " + invoicesWithoutStatus + " invoices");
} else {
    print("✓ All invoices already have status field");
}

// Step 2: Add is_auto_generated_status field with default TRUE
const invoicesWithoutAutoFlag = db.invoices.countDocuments({ isAutoGeneratedStatus: { $exists: false } });
if (invoicesWithoutAutoFlag > 0) {
    db.invoices.updateMany(
        { isAutoGeneratedStatus: { $exists: false } },
        {
            $set: {
                isAutoGeneratedStatus: true
            }
        }
    );
    print("✓ Set isAutoGeneratedStatus to true for " + invoicesWithoutAutoFlag + " invoices");
} else {
    print("✓ All invoices already have isAutoGeneratedStatus field");
}

// Step 3: Initialize timestamp fields if they don't exist
const timestampFields = [
    'lastStatusUpdatedAt',
    'emailSentAt',
    'firstViewedAt',
    'paidAt'
];

timestampFields.forEach(field => {
    const count = db.invoices.countDocuments({ [field]: { $exists: false } });
    if (count > 0) {
        db.invoices.updateMany(
            { [field]: { $exists: false } },
            {
                $set: {
                    [field]: null
                }
            }
        );
        print("✓ Initialized " + field + " field for " + count + " invoices");
    }
});

// Step 4: Migrate Razorpay fields from nested PaymentDetails to top level
// Check if any invoices have payment details with Razorpay IDs
const invoicesWithNestedPaymentDetails = db.invoices.find({
    "paymentDetails.razorpayPaymentLinkId": { $exists: true }
}).toArray();

if (invoicesWithNestedPaymentDetails.length > 0) {
    print("\n✓ Found " + invoicesWithNestedPaymentDetails.length + " invoices with nested payment details");
    
    invoicesWithNestedPaymentDetails.forEach(invoice => {
        const updateFields = {};
        
        // Migrate Razorpay fields to top level
        if (invoice.paymentDetails.razorpayPaymentLinkId) {
            updateFields.razorpayPaymentLinkId = invoice.paymentDetails.razorpayPaymentLinkId;
        }
        if (invoice.paymentDetails.razorpayOrderId) {
            updateFields.razorpayOrderId = invoice.paymentDetails.razorpayOrderId;
        }
        if (invoice.paymentDetails.razorpayPaymentId) {
            updateFields.razorpayPaymentId = invoice.paymentDetails.razorpayPaymentId;
        }
        
        // Migrate payment status to top level
        if (invoice.paymentDetails.paymentStatus) {
            updateFields.paymentStatus = invoice.paymentDetails.paymentStatus;
        }
        
        if (Object.keys(updateFields).length > 0) {
            db.invoices.updateOne(
                { _id: invoice._id },
                { $set: updateFields }
            );
        }
    });
    
    print("✓ Migrated Razorpay fields from nested PaymentDetails to top level");
}

// Step 5: Initialize Razorpay fields at top level if they don't exist
const razorpayFields = [
    'razorpayPaymentLinkId',
    'razorpayOrderId',
    'razorpayPaymentId'
];

razorpayFields.forEach(field => {
    const count = db.invoices.countDocuments({ [field]: { $exists: false } });
    if (count > 0) {
        db.invoices.updateMany(
            { [field]: { $exists: false } },
            {
                $set: {
                    [field]: null
                }
            }
        );
        print("✓ Initialized " + field + " field for " + count + " invoices");
    }
});

// Step 6: Initialize payment_status field at top level with default PENDING
const invoicesWithoutPaymentStatus = db.invoices.countDocuments({ 
    paymentStatus: { $exists: false } 
});

if (invoicesWithoutPaymentStatus > 0) {
    db.invoices.updateMany(
        { paymentStatus: { $exists: false } },
        {
            $set: {
                paymentStatus: "PENDING"
            }
        }
    );
    print("✓ Set paymentStatus to PENDING for " + invoicesWithoutPaymentStatus + " invoices");
} else {
    print("✓ All invoices already have paymentStatus field");
}

// Step 7: Update payment status based on invoice status for existing invoices
const paidInvoices = db.invoices.countDocuments({ 
    status: "PAID",
    paymentStatus: { $nin: ["SUCCESS", "PAID"] }
});

if (paidInvoices > 0) {
    db.invoices.updateMany(
        { 
            status: "PAID",
            paymentStatus: { $nin: ["SUCCESS", "PAID"] }
        },
        {
            $set: {
                paymentStatus: "SUCCESS"
            }
        }
    );
    print("✓ Updated paymentStatus to SUCCESS for " + paidInvoices + " invoices with PAID status");
}

// Migrate old PAID payment status to SUCCESS
const oldPaidPaymentStatus = db.invoices.countDocuments({
    paymentStatus: "PAID"
});

if (oldPaidPaymentStatus > 0) {
    db.invoices.updateMany(
        { paymentStatus: "PAID" },
        {
            $set: {
                paymentStatus: "SUCCESS"
            }
        }
    );
    print("✓ Migrated " + oldPaidPaymentStatus + " invoices from PAID to SUCCESS payment status");
}

// Migrate old REFUNDED payment status to FAILED (as REFUNDED is no longer supported)
const oldRefundedPaymentStatus = db.invoices.countDocuments({
    paymentStatus: "REFUNDED"
});

if (oldRefundedPaymentStatus > 0) {
    db.invoices.updateMany(
        { paymentStatus: "REFUNDED" },
        {
            $set: {
                paymentStatus: "FAILED"
            }
        }
    );
    print("✓ Migrated " + oldRefundedPaymentStatus + " invoices from REFUNDED to FAILED payment status");
}

// Step 8: Set lastStatusUpdatedAt for invoices that don't have it
const invoicesWithoutLastStatusUpdate = db.invoices.countDocuments({
    lastStatusUpdatedAt: null,
    lastUpdatedAt: { $exists: true }
});

if (invoicesWithoutLastStatusUpdate > 0) {
    db.invoices.updateMany(
        {
            lastStatusUpdatedAt: null,
            lastUpdatedAt: { $exists: true }
        },
        [
            {
                $set: {
                    lastStatusUpdatedAt: "$lastUpdatedAt"
                }
            }
        ]
    );
    print("✓ Set lastStatusUpdatedAt from lastUpdatedAt for " + invoicesWithoutLastStatusUpdate + " invoices");
}

// Verification: Count invoices with all required fields
print("\n=== Migration Verification ===");

const totalInvoices = db.invoices.countDocuments({});
print("Total invoices: " + totalInvoices);

const verificationChecks = [
    { field: "status", expected: totalInvoices },
    { field: "isAutoGeneratedStatus", expected: totalInvoices },
    { field: "lastStatusUpdatedAt", expected: totalInvoices },
    { field: "emailSentAt", expected: totalInvoices },
    { field: "firstViewedAt", expected: totalInvoices },
    { field: "paidAt", expected: totalInvoices },
    { field: "razorpayPaymentLinkId", expected: totalInvoices },
    { field: "razorpayOrderId", expected: totalInvoices },
    { field: "razorpayPaymentId", expected: totalInvoices },
    { field: "paymentStatus", expected: totalInvoices }
];

let allChecksPassed = true;

verificationChecks.forEach(check => {
    const count = db.invoices.countDocuments({ [check.field]: { $exists: true } });
    const status = count === check.expected ? "✓" : "✗";
    print(status + " " + check.field + ": " + count + "/" + check.expected);
    
    if (count !== check.expected) {
        allChecksPassed = false;
    }
});

// Verify enum values are valid
const validStatuses = ["DRAFT", "SENT", "VIEWED", "PAID", "OVERDUE", "CANCELLED"];
const invalidStatusCount = db.invoices.countDocuments({
    status: { $nin: validStatuses }
});

if (invalidStatusCount > 0) {
    print("✗ Found " + invalidStatusCount + " invoices with invalid status values");
    allChecksPassed = false;
} else {
    print("✓ All invoice statuses are valid");
}

const validPaymentStatuses = ["PENDING", "SUCCESS", "FAILED"];
const invalidPaymentStatusCount = db.invoices.countDocuments({
    paymentStatus: { $nin: validPaymentStatuses }
});

if (invalidPaymentStatusCount > 0) {
    print("✗ Found " + invalidPaymentStatusCount + " invoices with invalid payment status values");
    allChecksPassed = false;
} else {
    print("✓ All payment statuses are valid");
}

// Summary
print("\n=== Migration Summary ===");
if (allChecksPassed) {
    print("✓ Migration completed successfully!");
    print("✓ All " + totalInvoices + " invoices have been updated with required fields");
} else {
    print("⚠ Warning: Some verification checks failed");
    print("⚠ Please review the migration results above");
}

// Display sample invoice to verify structure
print("\n=== Sample Invoice Structure ===");
const sampleInvoice = db.invoices.findOne({});
if (sampleInvoice) {
    print("Invoice ID: " + sampleInvoice._id);
    print("Status: " + sampleInvoice.status);
    print("Payment Status: " + sampleInvoice.paymentStatus);
    print("Is Auto Generated Status: " + sampleInvoice.isAutoGeneratedStatus);
    print("Last Status Updated At: " + sampleInvoice.lastStatusUpdatedAt);
    print("Email Sent At: " + sampleInvoice.emailSentAt);
    print("First Viewed At: " + sampleInvoice.firstViewedAt);
    print("Paid At: " + sampleInvoice.paidAt);
    print("Razorpay Payment Link ID: " + sampleInvoice.razorpayPaymentLinkId);
    print("Razorpay Order ID: " + sampleInvoice.razorpayOrderId);
    print("Razorpay Payment ID: " + sampleInvoice.razorpayPaymentId);
}

print("\n=== Migration Complete ===");
