spring.data.mongodb.uri=mongodb://localhost:27017/Invoizo

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://tidy-llama-24.clerk.accounts.dev
clerk.jwks-url=https://tidy-llama-24.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=pk_test_dGlkeS1sbGFtYS0yNC5jbGVyay5hY2NvdW50cy5kZXYk

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9665a7001@smtp-brevo.com
spring.mail.password=tTS59AqNX4jywQ2c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=vairag.techwork@gmail.com

# Encryption Configuration
encryption.secret.key=${ENCRYPTION_SECRET_KEY:}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_RgUK2syr4q4GqY}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:V1Xo7qH71Ulp3kU127dMKLqL}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:Vairag@310}

# Application Configuration
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
