package in.invoizo.invoicegeneratorapi.entity;

import java.time.Instant;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

@Data
@Document(collection = "invoices")
@CompoundIndexes({
    @CompoundIndex(name = "clerkId_status_idx", def = "{'clerkId': 1, 'status': 1}"),
    @CompoundIndex(name = "clerkId_dueDate_idx", def = "{'clerkId': 1, 'invoice.dueDate': 1}")
})
public class Invoice {
    @Id
    private String id;

    private Company company;
    private Billing billing;
    private Shipping shipping;
    private InvoiceDetails invoice;
    private List<Item> items;
    private String notes;
    private String logo;
    private double tax;
    private String clerkId;
    @CreatedDate
    private Instant createdAt;

    @LastModifiedDate
    private Instant lastUpdatedAt;
    private String thumbnailUrl;
    private String template;
    private String title;

    // New fields for status tracking (Requirements 8.1, 8.2, 8.3, 8.4, 8.5, 8.6)
    private InvoiceStatus status;
    private Boolean isAutoGeneratedStatus = true;
    private Instant lastStatusUpdatedAt;
    private Instant emailSentAt;
    private Instant firstViewedAt;
    private Instant paidAt;
    private Instant cancelledAt;

    // Razorpay payment integration fields (Requirements 8.7, 8.8, 8.9)
    private String razorpayPaymentLinkId;
    private String razorpayOrderId;
    private String razorpayPaymentId;
    
    // Payment status field (Requirement 8.10)
    private PaymentStatus paymentStatus;

    // New fields for GST
    private GSTDetails gstDetails;
    private String companyGSTNumber;
    private TransactionType transactionType;

    // Payment related fields (legacy - keeping for backward compatibility)
    private PaymentDetails paymentDetails;
    private List<PaymentReminder> paymentReminders;

    @Data
    public static class Company {
        private String name;
        private String phone;
        private String address;
    }

    @Data
    public static class Billing {
        private String name;
        private String phone;
        private String address;
        private String email; // Email address for sending invoices
    }

    @Data
    public static class Shipping {
        private String name;
        private String phone;
        private String address;
    }

    @Data
    public static class InvoiceDetails {
        private String number;
        private String date;
        private String dueDate;
    }

    @Data
    public static class Item {
        private String name;
        private int qty;
        private double amount;
        private String description;
        
        // New GST calculation fields
        private double gstRate;
        private double cgstAmount;
        private double sgstAmount;
        private double igstAmount;
        private double totalWithGST;
    }

    @Data
    public static class GSTDetails {
        private double cgstTotal;
        private double sgstTotal;
        private double igstTotal;
        private double gstTotal;
    }

    public enum InvoiceStatus {
        DRAFT, SENT, VIEWED, PAID, OVERDUE, CANCELLED
    }

    public enum TransactionType {
        INTRA_STATE, INTER_STATE
    }

    @Data
    public static class PaymentDetails {
        private PaymentMethod paymentMethod;
        private PaymentStatus paymentStatus;
        private double totalAmount;
        private String currency;
        private Instant paymentDate;
        private String paymentLink;
        private boolean cashPaymentAllowed;
        
        // Razorpay specific fields
        private String razorpayPaymentLinkId;
        private String razorpayOrderId;
        private String razorpayPaymentId;
        private String razorpaySignature;
        private Instant paymentLinkCreatedAt;
        private Instant paymentLinkExpiresAt;
        private String paymentReferenceId;
        private String webhookEventId; // For idempotency
        private String qrCodeData; // QR code data for payment
    }

    @Data
    public static class PaymentReminder {
        private String id;
        private ReminderType type;
        private Instant scheduledDate;
        private Instant sentDate;
        private boolean sent;
        private String emailSubject;
        private String emailBody;
    }

    public enum PaymentMethod {
        CASH, BANK_TRANSFER, RAZORPAY_UPI, RAZORPAY_CARD, RAZORPAY_NETBANKING, RAZORPAY_WALLET, RAZORPAY_OTHER
    }

    public enum PaymentStatus {
        PENDING, SUCCESS, FAILED
    }

    public enum ReminderType {
        TWO_DAYS_BEFORE, DUE_DATE, OVERDUE
    }
}